### PR TITLE
Better parsing of querystring

### PR DESCRIPTION
**Pull request by fle**
Preserve GET parameters with mumtiple values.
Add corresponding test too.

### CODE REVIEW

**Comment by birdsarah** [comment]
Hi Florent, this looks good. I think you didn't push the test.

**Comment by fle** [comment]
My branch looks OK ... I can't understand why there is a trouble here ...

**Comment by birdsarah** [comment]
It's here now!

**Comment by fle** [comment]
Can't figure why test coverage has decreased oO !

**Comment by birdsarah** [comment]
The coverage is to do with imports - nothing to worry about.

**Comment by birdsarah** [comment]
Thanks @fle!

**Pull request merged**
